export const products = [
  {
    id: 1,
    name: "Acer Swift Go 14",
    image: "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/306039_0_wdg8cc.png?tr=w-400",
    price: 50000,
    originalPrice: 60000,
    discount: "20% OFF",
    rating: 4.5,
    isBestSeller: true,
    brand: "Acer",
  },
  {
    id: 2,
    name: "JBL True Wireless Headphone",
    image: "https://www.skullcandy.eu/cdn/shop/files/CrusherANC2_Black_1.png?v=1768502942",
    price: 3000,
    originalPrice: 4000,
    discount: "25% OFF",
    rating: 4.2,
    isBestSeller: false,
    brand: "JBL",
  },
  {
    id: 3,
    name: "Samsung Galaxy S25 Ultra",
    image: "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Communication/Mobiles/Images/313339_0_a8qkjh.png?tr=w-400",
    price: 129999,
    originalPrice: 145000,
    discount: "10% OFF",
    rating: 4.8,
    isBestSeller: true,
    brand: "Samsung",
  },
  {
    id: 4,
    name: "Apple MacBook Air M3",
    image: "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/311850_0_kguryc.png?tr=w-400",
    price: 114900,
    originalPrice: 134900,
    discount: "15% OFF",
    rating: 4.9,
    isBestSeller: true,
    brand: "Apple",
  },
  {
    id: 5,
    name: "Sony WH-1000XM5",
    image: "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Entertainment/Headphones%20and%20Earphones/Images/272419_jqvb9x.png?tr=w-400",
    price: 24990,
    originalPrice: 34990,
    discount: "29% OFF",
    rating: 4.7,
    isBestSeller: false,
    brand: "Sony",
  },
  {
    id: 6,
    name: "Dell XPS 15",
    image: "https://media-ik.croma.com/prod/https://media.tatacroma.com/Croma%20Assets/Computers%20Peripherals/Laptop/Images/306600_0_ueoh5m.png?tr=w-400",
    price: 89990,
    originalPrice: 109990,
    discount: "18% OFF",
    rating: 4.4,
    isBestSeller: false,
    brand: "Dell",
  },
];